### ISSUE TITLE
That's good package, but doesn't work on react socket.io-client.

### ISSUE THREAD

**Issue by David-fang0621** [mcity/Mcity-octane-examples#6]
Hello
I am very interested in your package, but I don't know how this package works on React.
That would be fine if this package is available in the react component.
Waiting for any advice.

**Comment by tsworman** [comment]
@David-fang0621 I assume you are interested in using Socket.IO with React? If so, many tutorial exist to walk you through this: https://www.valentinog.com/blog/socket-react/

This repository covers how to use a very specific API (Mcity OCTANE) and is not focused on usage of socket.io with various javascript libraries directly. If you are trying to interact with the API directly and experience issues, please let us know.
